services:
  client:
    container_name: debug_dev_client
    build: ./client
    image: debug_client
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: bash -c "http-server -p 8000"
  api:
    container_name: debug_dev_api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=tryforcetracker
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=tryforcetracker
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
networks:
  default:
    name: debug_api
